google_scraper_index:
  path: /
  controller: App\Controller\GoogleScraperController::index

google_scraper_api:
  path: /api/google-scraper
  controller: App\Controller\GoogleScraperApiController::index
